window.NOTATR_POLICY_LOCALES = window.NOTATR_POLICY_LOCALES || {};
window.NOTATR_POLICY_LOCALES.FR = {
  "code": "fr",
  "name": "Français",
  "policy": "Politique de confidentialité",
  "updated": "Dernière mise à jour : août 2026",
  "language": "Langue",
  "pages": {
    "nat": {
      "htmlTitle": "Politique de confidentialité - Not a Translator",
      "product": "Not a Translator (extension de navigateur)",
      "tldr": "<strong>En bref :</strong> Not a Translator ne collecte pas de données personnelles, ne suit pas votre navigation, n'affiche pas de publicité et ne revend aucune donnée. Les seules informations traitées servent aux définitions, aux images illustratives, aux fonctions locales et à la mise en cache technique.",
      "sections": [
        { "h": "Ce que fait l'extension", "b": [{ "p": "Not a Translator est une extension de dictionnaire et d'aide à la lecture. Quand vous survolez ou sélectionnez un mot ou une expression, elle peut afficher une définition, une aide de lecture, une prononciation, une image illustrative, une conversion d'unité ou d'heure, ou un mode console lorsque la page ne permet pas d'afficher correctement l'infobulle." }] },
        { "h": "Données traitées", "b": [{ "p": "Pour effectuer une recherche, l'extension traite uniquement le mot ou l'expression choisi, ainsi que les réglages nécessaires au fonctionnement local. Selon la fonction utilisée, cette recherche peut être envoyée à un service de dictionnaire, d'image, de prononciation, de lemmatisation ou de cache." }, { "p": "L'extension ne transmet pas volontairement votre nom, votre adresse e-mail, vos comptes, vos mots de passe, votre historique de navigation, le contenu complet des pages visitées, ni une liste des sites consultés." }] },
        { "h": "Ce qui n'est pas collecté", "b": [{ "list": ["Aucune information personnelle identifiable.", "Aucun compte utilisateur dans l'extension.", "Aucune donnée de paiement traitée par l'extension.", "Aucun historique de navigation conservé.", "Aucune géolocalisation demandée ou utilisée.", "Aucun suivi publicitaire, analytique ou comportemental.", "Aucune vente, location ou transmission à des courtiers en données."] }] },
        { "h": "Services externes utilisés", "b": [{ "p": "Les services externes reçoivent uniquement les éléments nécessaires à la fonction demandée. Comme pour toute requête web, ils peuvent techniquement voir l'adresse IP associée à la requête, mais Not a Translator n'ajoute pas d'identifiant publicitaire ou de profil utilisateur." }, { "list": ["<strong>Merriam-Webster / dictionaryapi.com</strong> - définitions anglaises.", "<strong>Wiktionary</strong> - définitions, prononciations, formes et informations lexicales.", "<strong>RAE / DLE</strong> - définitions espagnoles.", "<strong>Larousse</strong> - définitions françaises.", "<strong>DWDS</strong> - définitions allemandes.", "<strong>Dizionario Internazionale, Hoepli</strong> - définitions italiennes.", "<strong>Kielitoimiston sanakirja</strong> - définitions finnoises.", "<strong>Logeion, Perseus</strong> - ressources grecques et latines anciennes.", "<strong>LINDAT / UDPipe</strong> - lemmatisation.", "<strong>Google Translate, MyMemory, AdminForge</strong> - aides ponctuelles de traduction lorsque l'utilisateur les demande ou les active.", "<strong>Sound of Text</strong> - audio lorsqu'une prononciation est demandée.", "<strong>notatr-proxy</strong> - proxy Cloudflare opéré par le développeur, notamment pour protéger des clés d'API et gérer des recherches d'images.", "<strong>Unsplash et Openverse</strong> - images illustratives via le proxy. Les recherches Unsplash utilisent le filtre de contenu strict."] }] },
        { "h": "Images et contenu adapté aux enfants", "b": [{ "p": "L'application est pensée pour rester adaptée aux enfants. Les images issues d'Unsplash sont demandées avec le filtre de contenu strict. Elles servent uniquement à accompagner une définition ou une recherche lexicale." }, { "p": "Les images et définitions proviennent toutefois de services externes et de ressources publiques. Si un contenu inadapté apparaît, il peut être signalé afin que la mise en cache ou le comportement de recherche soit corrigé." }] },
        { "h": "Mise en cache", "b": [{ "p": "Pour rendre le service plus rapide et limiter les appels répétés aux mêmes sources, certaines définitions, réponses techniques et recherches d'images peuvent être mises en cache localement dans le navigateur ou sur des services techniques opérés par le développeur. Le cache est organisé autour du mot, de l'expression ou de la requête utile, pas autour d'une identité utilisateur." }, { "p": "Les définitions mises en cache peuvent être consultées et surveillées par le développeur afin d'éviter les dérives, détecter des attaques, supprimer des contenus problématiques, améliorer la qualité du service et suivre l'utilisation générale. Cette surveillance ne sert pas à établir un profil individuel." }] },
        { "h": "Données stockées sur votre appareil", "b": [{ "p": "L'extension peut stocker des réglages nécessaires : activation, dictionnaire choisi, préférences d'affichage, couleur ou opacité de l'infobulle, état du mode console, dernière sélection utile au fonctionnement immédiat et préférences similaires." }, { "p": "Ces données sont des réglages techniques, pas un historique de navigation. Selon le navigateur et la synchronisation du profil, certains réglages peuvent être synchronisés entre vos appareils par Chrome, Firefox ou Safari." }] },
        { "h": "Statistiques des boutiques d'extensions", "b": [{ "p": "Le Chrome Web Store et les autres plateformes peuvent publier ou afficher au développeur des statistiques agrégées, par exemple le nombre d'utilisateurs par système d'exploitation, pays ou version. Ces données viennent de la boutique et ne permettent pas à Not a Translator d'identifier un utilisateur précis." }] },
        { "h": "Publicité et dons", "b": [{ "p": "Not a Translator n'affiche pas de publicité. Le projet repose sur les dons facultatifs, traités hors de l'extension par des services externes comme PayPal ou Buy Me a Coffee." }, { "p": "L'intention de financement est la suivante : 30 % des dons sont reversés à des organismes de charité, et 30 % sont réinvestis dans le développement de l'application. Le reste contribue aux coûts, au temps de maintenance et à la continuité du projet." }] },
        { "h": "Enfants", "b": [{ "p": "Not a Translator est un outil de dictionnaire et d'aide à la lecture adapté à un usage familial et scolaire. L'extension ne collecte pas sciemment de données personnelles auprès des enfants et n'intègre ni publicité ni suivi comportemental." }] },
        { "h": "Sécurité", "b": [{ "p": "Le développeur peut surveiller les caches, erreurs techniques et usages anormaux afin de protéger le service contre les abus, les attaques, le spam, les contenus détournés ou les dérives de qualité. Cette surveillance vise la sécurité et la fiabilité, pas le suivi individuel." }] },
        { "h": "Modifications", "b": [{ "p": "Cette politique peut être mise à jour lorsque l'extension évolue. La date de dernière mise à jour sera alors modifiée." }] },
        { "h": "Contact", "b": [{ "p": "Pour toute question : <a href=\"mailto:masquages-magie0r@icloud.com\">masquages-magie0r@icloud.com</a>" }] }
      ],
      "footer": "© 2026 Not a Translator · Cette politique s'applique à l'extension principale « Not a Translator »."
    },
    "experiment": {
      "htmlTitle": "Politique de confidentialité - Not a Translator Experiment",
      "product": "Not a Translator Experiment (extension de navigateur)",
      "tldr": "<strong>En bref :</strong> Cette extension compagnon envoie seulement le mot ou l'expression survolé ou sélectionné aux services nécessaires pour afficher images, mots liés, SenseMap et RootMap. Elle ne collecte pas votre identité, votre historique ou votre localisation. Elle ne vous piste pas, n'affiche pas de publicité et ne vend aucune donnée.",
      "sections": [
        { "h": "Ce que fait l'extension", "b": [{ "p": "Not a Translator Experiment enrichit l'infobulle du dictionnaire Not a Translator avec une image illustrative, un graphe des sens liés (SenseMap) et un graphe de la famille et de l'origine du mot (RootMap). Ces fonctions sont déclenchées uniquement par le mot ou l'expression que vous survolez ou sélectionnez." }] },
        { "h": "Données traitées", "b": [{ "p": "Pour une recherche, l'extension transmet uniquement le mot ou l'expression choisi. Elle ne transmet pas la page courante, son URL, le texte autour, votre identité ou un autre contenu de page." }] },
        { "h": "Ce qui n'est pas collecté", "b": [{ "list": ["Aucune information personnelle identifiable.", "Aucun compte, mot de passe ou donnée d'authentification.", "Aucune information financière ou de paiement.", "Aucun historique de navigation, liste de pages visitées ou URL.", "Aucune géolocalisation.", "Aucun clic, frappe clavier, suivi de souris ou analytique.", "Aucune publicité, aucun profilage, aucune vente ou transmission à des courtiers en données."] }] },
        { "h": "Services externes contactés", "b": [{ "p": "Chaque service reçoit seulement le mot ou l'expression recherché, et seulement pour la fonction qu'il alimente." }, { "list": ["<strong>Wiktionary</strong> - définitions, synonymes, antonymes, famille du mot et étymologie.", "<strong>notatr-proxy</strong> - Cloudflare Worker opéré par le développeur ; cache les recherches d'images et protège les identifiants d'API.", "<strong>Unsplash et Openverse</strong> - photographies illustratives via le proxy. Unsplash utilise le filtre de contenu strict.", "<strong>iNaturalist, GBIF, Wikidata, Wikimedia Commons</strong> - photographies d'espèces et d'objets.", "<strong>OpenStreetMap / Nominatim</strong> - miniatures de cartes pour les noms de lieux.", "<strong>LINDAT / UDPipe</strong> - lemmatisation."] }, { "p": "Ces services reçoivent les requêtes selon leurs propres politiques. Ils peuvent techniquement voir l'adresse IP d'origine ; l'extension ne l'ajoute pas et ne la stocke pas." }] },
        { "h": "Clé donateur", "b": [{ "p": "Certaines fonctions sont réservées aux donateurs. Un donateur peut recevoir une clé signée comme <code>NTX-XXXXX-XXXXX-XXXXX-XXXXXX</code> et la coller dans le popup." }, { "p": "La clé est dérivée de l'adresse e-mail du donateur mais ne la contient pas : seul un fingerprint salé et irréversible y est intégré. Elle est envoyée uniquement aux services du développeur pour validation et autorisation, jamais aux fournisseurs tiers." }, { "p": "Comme la même clé accompagne ces validations, les services du développeur pourraient techniquement relier plusieurs requêtes à la même clé. Aucun journal associant clés et mots recherchés n'est conservé, et la clé ne peut pas être reconvertie en adresse e-mail." }] },
        { "h": "Mise en cache", "b": [{ "p": "Les résultats peuvent être mis en cache en mémoire du navigateur et sur le cache Cloudflare ou serveur du développeur. Le cache est indexé par mot ou expression, pas par identité utilisateur, et peut être surveillé pour éviter abus, attaques et dérives de contenu." }] },
        { "h": "Données stockées sur votre appareil", "b": [{ "p": "L'extension stocke des réglages locaux comme l'activation, les options images, SenseMap et RootMap, ainsi que l'état de validation de la clé donateur le cas échéant. Elle ne stocke pas d'historique de recherche, de pages ou de documents." }] },
        { "h": "Dons", "b": [{ "p": "Les dons sont facultatifs et traités hors de l'extension. Si vous envoyez un e-mail après un don, votre adresse sert seulement à répondre, envoyer le lien d'installation et générer la clé donateur, pas au marketing." }] },
        { "h": "Enfants", "b": [{ "p": "L'extension est conçue pour rester adaptée aux enfants. Les images Unsplash utilisent le filtre de contenu strict, et il n'y a ni publicité ni suivi comportemental." }] },
        { "h": "Modifications", "b": [{ "p": "Cette politique peut être mise à jour lorsque les fonctions évoluent." }] },
        { "h": "Contact", "b": [{ "p": "Questions sur cette politique : <a href=\"mailto:bongo_plats@icloud.com\">bongo_plats@icloud.com</a>" }] }
      ],
      "footer": "© 2026 Not a Translator · Cette politique s'applique à l'extension « Not a Translator Experiment ». L'édition Pro a sa <a href=\"privacy-pro.html\">propre politique</a>."
    },
    "pro": {
      "htmlTitle": "Politique de confidentialité - Not a Translator Experiment Pro",
      "product": "Not a Translator Experiment Pro (extension de navigateur)",
      "tldr": "<strong>En bref :</strong> Cette extension envoie seulement le mot ou l'expression recherché aux services nécessaires. La liseuse et le lecteur PDF traitent le contenu des pages et documents entièrement sur votre appareil. Elle ne collecte pas votre identité, votre historique ou votre localisation, ne vous piste pas, n'affiche pas de publicité et ne vend aucune donnée.",
      "sections": [
        { "h": "Ce que fait l'extension", "b": [{ "p": "Not a Translator Experiment Pro enrichit l'infobulle Not a Translator avec images, SenseMap et RootMap, et ajoute une liseuse ainsi qu'un lecteur PDF pour utiliser les mêmes infobulles dans les longs textes et les documents PDF." }] },
        { "h": "Liseuse et lecteur PDF : traitement local", "b": [{ "list": ["La liseuse analyse la page courante dans votre navigateur pour extraire l'article et retirer menus, publicités et colonnes latérales.", "Le lecteur PDF télécharge le PDF que vous choisissez explicitement d'ouvrir depuis son site d'hébergement et le rend localement.", "Aucun contenu de page, contenu de document ou nom de fichier n'est envoyé au développeur ou à des tiers par ces fonctions. Seuls les mots individuels que vous recherchez quittent le navigateur."] }] },
        { "h": "Accès large aux sites", "b": [{ "p": "L'édition Pro peut demander l'accès à tous les sites (<code>&lt;all_urls&gt;</code>) parce qu'un PDF peut être hébergé sur n'importe quel domaine et que la liseuse fonctionne sur la page que vous lisez. Cette permission ne sert pas à inventorier les sites visités." }] },
        { "h": "Données traitées", "b": [{ "p": "Pour les recherches, l'extension transmet uniquement le mot ou l'expression choisi. Elle ne transmet pas la page complète, l'URL, le texte autour, votre identité ou un autre contenu." }] },
        { "h": "Ce qui n'est pas collecté", "b": [{ "list": ["Aucune information personnelle identifiable.", "Aucun compte, mot de passe ou donnée d'authentification.", "Aucune information financière ou de paiement.", "Aucun historique de navigation ou URL.", "Aucune géolocalisation.", "Aucune analytique, publicité ou suivi comportemental.", "Aucune vente ou transmission à des courtiers en données."] }] },
        { "h": "Services externes contactés", "b": [{ "p": "Chaque service externe reçoit seulement le mot ou l'expression recherché, et seulement pour la fonction qu'il alimente." }, { "list": ["<strong>Wiktionary</strong> - définitions, synonymes, antonymes, famille du mot et étymologie.", "<strong>notatr-proxy</strong> - Cloudflare Worker opéré par le développeur ; cache les recherches d'images et protège les identifiants d'API.", "<strong>Unsplash et Openverse</strong> - photographies illustratives via le proxy, avec filtre strict pour Unsplash.", "<strong>iNaturalist, GBIF, Wikidata, Wikimedia Commons</strong> - photographies d'espèces et d'objets.", "<strong>OpenStreetMap / Nominatim</strong> - miniatures de cartes pour les noms de lieux.", "<strong>LINDAT / UDPipe</strong> - lemmatisation."] }] },
        { "h": "Clé donateur", "b": [{ "p": "Certaines fonctions sont réservées aux donateurs et peuvent utiliser une clé signée. Elle contient seulement un fingerprint salé et irréversible dérivé de l'adresse e-mail du donateur et n'est envoyée qu'aux services du développeur pour validation et autorisation." }] },
        { "h": "Mise en cache", "b": [{ "p": "Les résultats peuvent être mis en cache en mémoire du navigateur et sur le cache Cloudflare ou serveur du développeur. Le cache est indexé par mot ou expression, pas par identité utilisateur, et peut être surveillé pour prévenir abus, attaques et dérives." }] },
        { "h": "Données stockées sur votre appareil", "b": [{ "p": "Les réglages locaux incluent les options de fonctions, l'état de validation de la clé donateur le cas échéant, les préférences liseuse/PDF et l'état temporaire nécessaire. Aucun historique de recherche ni contenu de page ou document n'est stocké comme profil utilisateur." }] },
        { "h": "Dons", "b": [{ "p": "Les dons sont facultatifs et traités hors de l'extension. Les échanges par e-mail après un don servent uniquement à répondre, envoyer le lien d'installation et générer une clé donateur, pas au marketing." }] },
        { "h": "Enfants", "b": [{ "p": "L'extension est conçue pour rester adaptée aux enfants. Les images Unsplash utilisent le filtre de contenu strict, et il n'y a ni publicité ni suivi comportemental." }] },
        { "h": "Modifications", "b": [{ "p": "Cette politique peut être mise à jour lorsque les fonctions évoluent." }] },
        { "h": "Contact", "b": [{ "p": "Questions sur cette politique : <a href=\"mailto:bongo_plats@icloud.com\">bongo_plats@icloud.com</a>" }] }
      ],
      "footer": "© 2026 Not a Translator · Cette politique s'applique à l'extension « Not a Translator Experiment Pro ». L'édition non-Pro a sa <a href=\"privacy.html\">propre politique</a>."
    }
  }
};
