window.NOTATR_POLICY_LOCALES = window.NOTATR_POLICY_LOCALES || {};
window.NOTATR_POLICY_LOCALES.DE = {
  "code": "de",
  "name": "Deutsch",
  "policy": "Datenschutzerklärung",
  "updated": "Zuletzt aktualisiert: August 2026",
  "language": "Sprache",
  "pages": {
    "nat": { "htmlTitle": "Datenschutzerklärung - Not a Translator", "product": "Not a Translator (Browser-Erweiterung)", "tldr": "<strong>Kurz gesagt:</strong> Not a Translator sammelt keine personenbezogenen Daten, verfolgt Ihr Surfverhalten nicht, zeigt keine Werbung und verkauft keine Daten. Die verarbeiteten Informationen dienen nur Definitionen, illustrativen Bildern, lokalen Funktionen und technischem Caching.", "sections": [
      { "h": "Was die Erweiterung tut", "b": [{ "p": "Not a Translator ist eine Wörterbuch- und Lesehilfe-Erweiterung. Wenn Sie ein Wort oder einen Ausdruck markieren oder darüberfahren, kann sie eine Definition, Lesehilfe, Aussprache, ein illustratives Bild, eine Einheiten- oder Zeitumrechnung oder einen Konsolenmodus anzeigen, wenn die Seite den Tooltip nicht zuverlässig darstellen kann." }] },
      { "h": "Verarbeitete Daten", "b": [{ "p": "Für eine Suche verarbeitet die Erweiterung nur das gewählte Wort oder den Ausdruck sowie die für den lokalen Betrieb nötigen Einstellungen. Je nach Funktion kann die Anfrage an einen Wörterbuch-, Bild-, Aussprache-, Lemmatisierungs- oder Cache-Dienst gesendet werden." }, { "p": "Die Erweiterung übermittelt nicht absichtlich Namen, E-Mail-Adressen, Konten, Passwörter, Browserverlauf, vollständige Seiteninhalte oder eine Liste besuchter Websites." }] },
      { "h": "Was nicht gesammelt wird", "b": [{ "list": ["Keine personenbezogenen Informationen.", "Kein Benutzerkonto in der Erweiterung.", "Keine Zahlungsdatenverarbeitung durch die Erweiterung.", "Kein gespeicherter Browserverlauf.", "Keine Geolokalisierung.", "Keine Werbung, Analyse oder Verhaltensverfolgung.", "Kein Verkauf, keine Vermietung und keine Weitergabe an Datenhändler."] }] },
      { "h": "Externe Dienste", "b": [{ "p": "Externe Dienste erhalten nur das, was für die angeforderte Funktion nötig ist. Wie bei jeder Webanfrage können sie technisch die IP-Adresse sehen; Not a Translator fügt jedoch keine Werbe-ID oder Nutzerprofile hinzu." }, { "list": ["<strong>Merriam-Webster / dictionaryapi.com</strong> - englische Definitionen.", "<strong>Wiktionary</strong> - Definitionen, Aussprachen, Formen und lexikalische Informationen.", "<strong>RAE / DLE</strong> - spanische Definitionen.", "<strong>Larousse</strong> - französische Definitionen.", "<strong>DWDS</strong> - deutsche Definitionen.", "<strong>Dizionario Internazionale, Hoepli</strong> - italienische Definitionen.", "<strong>Kielitoimiston sanakirja</strong> - finnische Definitionen.", "<strong>Logeion, Perseus</strong> - Ressourcen für Altgriechisch und Latein.", "<strong>LINDAT / UDPipe</strong> - Lemmatisierung.", "<strong>Google Translate, MyMemory, AdminForge</strong> - optionale Übersetzungshilfe, wenn Nutzer sie anfordern oder aktivieren.", "<strong>Sound of Text</strong> - Audio, wenn Aussprache angefordert wird.", "<strong>notatr-proxy</strong> - vom Entwickler betriebener Cloudflare-Proxy zum Schutz von API-Schlüsseln und für Bildsuchen.", "<strong>Unsplash und Openverse</strong> - illustrative Bilder über den Proxy. Unsplash nutzt den strengen Inhaltsfilter."] }] },
      { "h": "Bilder und kinderfreundliche Inhalte", "b": [{ "p": "Die Anwendung ist so gestaltet, dass sie für Kinder geeignet bleibt. Unsplash-Bilder werden mit strengem Inhaltsfilter angefordert und dienen nur der Illustration einer Definition oder Wortsuche." }, { "p": "Bilder und Definitionen stammen dennoch aus externen Diensten und öffentlichen Quellen. Ungeeignete Inhalte können gemeldet werden, damit Cache oder Suchverhalten korrigiert werden." }] },
      { "h": "Caching", "b": [{ "p": "Um den Dienst schnell zu halten, können Definitionen, technische Antworten und Bildsuchen lokal im Browser oder auf technischen Diensten des Entwicklers zwischengespeichert werden. Der Cache basiert auf Wort, Ausdruck oder nützlicher Anfrage, nicht auf Nutzeridentität." }, { "p": "Zwischengespeicherte Definitionen können geprüft werden, um Fehlentwicklungen zu vermeiden, Angriffe zu erkennen, problematische Inhalte zu entfernen, Qualität zu verbessern und allgemeine Nutzung zu verfolgen. Das dient nicht individuellen Profilen." }] },
      { "h": "Auf Ihrem Gerät gespeicherte Daten", "b": [{ "p": "Die Erweiterung kann notwendige Einstellungen speichern: Aktivierung, Wörterbuch, Darstellung, Tooltip-Farbe oder Deckkraft, Konsolenmodus, letzte für den unmittelbaren Betrieb nötige Auswahl und ähnliche Präferenzen." }, { "p": "Dies sind technische Einstellungen, kein Browserverlauf. Je nach Browser können manche Einstellungen durch Chrome, Firefox oder Safari zwischen Geräten synchronisiert werden." }] },
      { "h": "Statistiken der Erweiterungs-Stores", "b": [{ "p": "Der Chrome Web Store und andere Plattformen können aggregierte Statistiken wie Nutzerzahlen nach Betriebssystem, Land oder Version anzeigen. Diese Store-Daten erlauben Not a Translator nicht, einzelne Nutzer zu identifizieren." }] },
      { "h": "Werbung und Spenden", "b": [{ "p": "Not a Translator zeigt keine Werbung. Das Projekt stützt sich auf freiwillige Spenden, die außerhalb der Erweiterung über Dienste wie PayPal oder Buy Me a Coffee verarbeitet werden." }, { "p": "Die Finanzierungsabsicht lautet: 30 % der Spenden gehen an Wohltätigkeitsorganisationen, und 30 % werden in die Entwicklung der Anwendung reinvestiert. Der Rest unterstützt Kosten, Wartung und Kontinuität." }] },
      { "h": "Kinder", "b": [{ "p": "Not a Translator ist ein Wörterbuch- und Lesehilfe-Werkzeug für Familien- und Schuleinsatz. Die Erweiterung sammelt wissentlich keine personenbezogenen Daten von Kindern und enthält keine Werbung oder Verhaltensverfolgung." }] },
      { "h": "Sicherheit", "b": [{ "p": "Der Entwickler kann Caches, technische Fehler und ungewöhnliche Nutzung überwachen, um den Dienst vor Missbrauch, Angriffen, Spam, zweckentfremdeten Inhalten und Qualitätsproblemen zu schützen. Diese Überwachung dient Sicherheit und Zuverlässigkeit, nicht individueller Verfolgung." }] },
      { "h": "Änderungen", "b": [{ "p": "Diese Richtlinie kann aktualisiert werden, wenn sich die Erweiterung weiterentwickelt." }] },
      { "h": "Kontakt", "b": [{ "p": "Fragen: <a href=\"mailto:masquages-magie0r@icloud.com\">masquages-magie0r@icloud.com</a>" }] }
    ], "footer": "© 2026 Not a Translator · Diese Richtlinie gilt für die Haupt-Erweiterung „Not a Translator“." },
    "experiment": { "htmlTitle": "Datenschutzerklärung - Not a Translator Experiment", "product": "Not a Translator Experiment (Browser-Erweiterung)", "tldr": "<strong>Kurz gesagt:</strong> Diese Begleiterweiterung sendet nur das markierte Wort oder den Ausdruck an die nötigen Dienste für Bilder, verwandte Wörter, SenseMap und RootMap. Sie sammelt keine Identität, keinen Browserverlauf und keinen Standort, verfolgt Sie nicht, zeigt keine Werbung und verkauft keine Daten.", "sections": [
      { "h": "Was die Erweiterung tut", "b": [{ "p": "Not a Translator Experiment ergänzt den Tooltip von Not a Translator um ein illustratives Bild, eine Karte verwandter Bedeutungen (SenseMap) und eine Karte der Wortfamilie und Herkunft (RootMap). Ausgelöst wird dies nur durch das markierte oder überfahrene Wort." }] },
      { "h": "Verarbeitete Daten", "b": [{ "p": "Für eine Suche übermittelt die Erweiterung nur das gewählte Wort oder den Ausdruck. Die aktuelle Seite, URL, der umgebende Text, Ihre Identität oder andere Seiteninhalte werden nicht gesendet." }] },
      { "h": "Was nicht gesammelt wird", "b": [{ "list": ["Keine personenbezogenen Informationen.", "Keine Konten, Passwörter oder Authentifizierungsdaten.", "Keine Zahlungsdaten.", "Kein Browserverlauf, keine URL-Liste.", "Keine Geolokalisierung.", "Keine Klick-, Tastatur-, Maus- oder Analysedaten.", "Keine Werbung, Profilbildung, Verkauf oder Weitergabe an Datenhändler."] }] },
      { "h": "Externe Dienste", "b": [{ "p": "Jeder Dienst erhält nur das nachgeschlagene Wort oder den Ausdruck und nur für die jeweilige Funktion." }, { "list": ["<strong>Wiktionary</strong> - Definitionen, Synonyme, Antonyme, Wortfamilie und Etymologie.", "<strong>notatr-proxy</strong> - Cloudflare Worker des Entwicklers; cached Bildsuchen und schützt API-Zugangsdaten.", "<strong>Unsplash und Openverse</strong> - illustrative Fotos über den Proxy; Unsplash nutzt strenge Filter.", "<strong>iNaturalist, GBIF, Wikidata, Wikimedia Commons</strong> - Fotos von Arten und Objekten.", "<strong>OpenStreetMap / Nominatim</strong> - Kartenminiaturen für Ortsnamen.", "<strong>LINDAT / UDPipe</strong> - Lemmatisierung."] }] },
      { "h": "Spender-Schlüssel", "b": [{ "p": "Einige Funktionen sind Spendern vorbehalten. Ein Spender kann einen signierten Schlüssel wie <code>NTX-XXXXX-XXXXX-XXXXX-XXXXXX</code> erhalten. Der Schlüssel enthält nur einen gesalzenen, irreversiblen Fingerabdruck der E-Mail-Adresse und wird nur an Entwicklerdienste zur Validierung gesendet." }] },
      { "h": "Caching", "b": [{ "p": "Ergebnisse können im Browser und auf dem Cloudflare-/Cache-Server des Entwicklers zwischengespeichert werden. Der Cache ist nach Wort oder Ausdruck, nicht nach Nutzeridentität, organisiert und kann zur Missbrauchsabwehr geprüft werden." }] },
      { "h": "Auf Ihrem Gerät gespeicherte Daten", "b": [{ "p": "Gespeichert werden lokale Einstellungen wie Aktivierung, Bilder, SenseMap, RootMap und ggf. der Status des Spender-Schlüssels. Es wird kein Such-, Seiten- oder Dokumentverlauf gespeichert." }] },
      { "h": "Spenden", "b": [{ "p": "Spenden sind freiwillig und werden außerhalb der Erweiterung verarbeitet. E-Mails nach einer Spende dienen nur Antwort, Installationslink und Schlüsselgenerierung, nicht Marketing." }] },
      { "h": "Kinder", "b": [{ "p": "Die Erweiterung ist kinderfreundlich ausgelegt. Unsplash-Bilder nutzen strenge Inhaltsfilter; es gibt keine Werbung oder Verhaltensverfolgung." }] },
      { "h": "Änderungen", "b": [{ "p": "Diese Richtlinie kann aktualisiert werden, wenn sich Funktionen ändern." }] },
      { "h": "Kontakt", "b": [{ "p": "Fragen: <a href=\"mailto:bongo_plats@icloud.com\">bongo_plats@icloud.com</a>" }] }
    ], "footer": "© 2026 Not a Translator · Diese Richtlinie gilt für „Not a Translator Experiment“. Die Pro-Ausgabe hat eine <a href=\"privacy-pro.html\">eigene Richtlinie</a>." },
    "pro": { "htmlTitle": "Datenschutzerklärung - Not a Translator Experiment Pro", "product": "Not a Translator Experiment Pro (Browser-Erweiterung)", "tldr": "<strong>Kurz gesagt:</strong> Diese Erweiterung sendet nur das nachgeschlagene Wort oder den Ausdruck an die nötigen Dienste. Reader und PDF-Viewer verarbeiten Seiten- und Dokumentinhalte vollständig auf Ihrem Gerät. Keine Identität, kein Verlauf, kein Standort, keine Werbung, kein Verkauf von Daten.", "sections": [
      { "h": "Was die Erweiterung tut", "b": [{ "p": "Not a Translator Experiment Pro ergänzt Tooltips um Bilder, SenseMap und RootMap und fügt Reader sowie PDF-Viewer hinzu, damit dieselben Tooltips in langen Texten und PDFs funktionieren." }] },
      { "h": "Reader und PDF-Viewer: lokale Verarbeitung", "b": [{ "list": ["Der Reader analysiert die aktuelle Seite lokal im Browser, um den Artikel zu extrahieren.", "Der PDF-Viewer lädt nur das ausdrücklich geöffnete PDF von seiner Hosting-Seite und rendert es lokal.", "Diese Funktionen senden keine Seiteninhalte, Dokumentinhalte oder Dateinamen an den Entwickler oder Dritte."] }] },
      { "h": "Breiter Website-Zugriff", "b": [{ "p": "Die Pro-Ausgabe kann Zugriff auf alle Websites (<code>&lt;all_urls&gt;</code>) benötigen, weil PDFs auf jeder Domain liegen können. Die Berechtigung wird nicht genutzt, um besuchte Websites zu inventarisieren." }] },
      { "h": "Daten, Grenzen und Dienste", "b": [{ "p": "Für Nachschlagen wird nur das gewählte Wort oder der Ausdruck übertragen. Es werden keine vollständigen Seiten, URLs, Profile, Zahlungsdaten, Geolokalisierung oder Verhaltensdaten gesammelt. Externe Dienste entsprechen denen der Experiment-Ausgabe, einschließlich notatr-proxy, Wiktionary, Unsplash/Openverse mit strengem Filter und LINDAT/UDPipe." }] },
      { "h": "Spender-Schlüssel, Cache und Gerät", "b": [{ "p": "Spenderfunktionen können einen signierten Schlüssel verwenden, der nur einen irreversiblen Fingerabdruck enthält. Ergebnisse können nach Wort oder Ausdruck gecached und zur Sicherheit geprüft werden. Lokale Einstellungen werden auf dem Gerät gespeichert; kein Suchverlauf oder Dokumentinhalt wird als Nutzerprofil gespeichert." }] },
      { "h": "Kinder, Spenden, Änderungen und Kontakt", "b": [{ "p": "Die Erweiterung bleibt kinderfreundlich, ohne Werbung oder Tracking. Spenden sind freiwillig und extern. Diese Richtlinie kann aktualisiert werden. Kontakt: <a href=\"mailto:bongo_plats@icloud.com\">bongo_plats@icloud.com</a>" }] }
    ], "footer": "© 2026 Not a Translator · Diese Richtlinie gilt für „Not a Translator Experiment Pro“. Die Nicht-Pro-Ausgabe hat eine <a href=\"privacy.html\">eigene Richtlinie</a>." }
  }
};
